{% set name = "marshmallow-oneofschema" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 68b4a57d0281a04ac25d4eb7a4c5865a57090a0a8fd30fd6362c8e833ac6a6d9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - flit-core <4
    - pip
  run:
    - python >=3.8
    - marshmallow >=3.0.0,<4.0.0

test:
  imports:
    - marshmallow_oneofschema

about:
  home: https://github.com/marshmallow-code/marshmallow-oneofschema
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Marshmallow library extension that allows schema (de)multiplexing

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
