{% set name = "marshmallow-oneofschema" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c06c8d9f14d51ffff152d66d85bd5f27d55cff10752a3b1f8c1f948bf5f597a0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - flit-core <4
    - pip
  run:
    - python >={{ python_min }}
    - marshmallow >=3.0.0,<4.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - marshmallow_oneofschema

about:
  home: https://github.com/marshmallow-code/marshmallow-oneofschema
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Marshmallow library extension that allows schema (de)multiplexing

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
